@extends('layouts.app')

@section('title') Privacy Policy | DRIVE | Roadside @endsection

@section('head')
@endsection


@section('header')
@endsection

@section('content')
    <!-- Contact Section -->
    <section class="terms-section">
        <div class="container">
            <div class="terms-content">
                <h2>Terms and conditions</h2>
                <p><b>DRIVE | Roadside Service Coverage</b></p>
                <p>The terms and conditions stated herein (collectively, this "Agreement") constitute a legal agreement between you and Mobile Roadside, LLC (“Mobile Roadside” or the "Company"). By using or receiving any services, apps, websites or other products, services or information supplied to you by the Company (collectively, the "Service"), and downloading, installing or using any associated software or apps supplied by the Company which purpose is to enable you to use the Service (collectively, the "Software"), you hereby expressly acknowledge and agree to be bound by the terms and conditions of this Agreement, and any future amendments and additions to this Agreement as published from time to time on the Company website or through the other Services.
                    </p>
                    <p>The Company reserves the right to modify the terms and conditions of this Agreement or its policies relating to the Service or Software at any time, effective upon posting of an updated version of this Agreement on the Service or Software. You are responsible for regularly reviewing this Agreement. Continued use of the Service or Software after any such changes shall constitute your consent to such changes. If you require any more information or have any questions about our Terms and Conditions, please feel free to contact us by email at info@driveroadside.com
                    </p>
                    <p>THE COMPANY DOES NOT PROVIDE ROADSIDE ASSISTANCE, TOWING SERVICES OR OTHER SERVICES FROM THIRD PARTIES IN OTHER CATEGORIES (COLLECTIVELY, THE “THIRD PARTY SERVICES”). THE COMPANY IS A DIRECTORY SERVICE HELPING USERS FIND THIRD PARTIES TO PROVIDE SUCH THIRD PARTY SERVICES (THE “THIRD PARTY SERVICE PROVIDERS”). IT IS UP TO THE THIRD PARTY SERVICE PROVIDER TO OFFER THEIR THIRD PARTY SERVICES, WHICH MAY BE SCHEDULED THROUGH USE OF THE COMPANY SOFTWARE OR SERVICE. THE COMPANY OFFERS INFORMATION AND A METHOD TO OBTAIN SUCH THIRD PARTY SERVICES FROM THIRD PARTY SERVICE PROVIDERS, BUT DOES NOT, AND DOES NOT INTEND TO, PROVIDE THIRD PARTY SERVICES OR ACT IN ANY WAY AS A THIRD PARTY SERVICE PROVIDER, AND HAS NO RESPONSIBILITY OR LIABILITY FOR ANY THIRD PARTY SERVICES PROVIDED TO (OR FAILED TO BE PROVIDED) NOR FOR THE ACTIONS OR INACTIONS OF ANY THIRD PARTY SERVICE PROVIDERS. ANY INDIVIDUALS WHO PROVIDE ANY THIRD PARTY SERVICES ARE NOT EMPLOYEES NOR CONTRACTORS OF COMPANY BUT RATHER OF THIRD PARTY SERVICE PROVIDERS, AND COMPANY IS NOT RESPONSIBLE FOR THEIR ACTIONS OR INACTIONS.
                    </p>
                <p><b>MOBILE ROADSIDE IS ONLY A VENUE</b></p>
                <p>
                    <b>Towing</b> The Service is a communications platform for enabling the connection between individuals seeking to obtain Third Party Services and/or individuals or companies seeking to provide Third Party Services. The Company does not guarantee or warrant, and makes no representations regarding, the reliability, quality or suitability of such Third Party Service Providers. When interacting with Third Party Service Providers you should exercise caution and common sense to protect your personal safety and property, just as you would when interacting with other persons whom you don't know. By using the Service, you agree to hold the Company free from the responsibility for any liability or damage that might arise out of the transactions involved. NEITHER THE COMPANY NOR ITS AFFILIATES OR LICENSORS IS RESPONSIBLE FOR THE CONDUCT, WHETHER ONLINE OR OFFLINE, OF ANY USER OF THE SERVICE OR THIRD PARTY SERVICES NOR ANY THIRD PARTY SERVICE PROVIDERS. THE COMPANY AND ITS AFFILIATES AND LICENSORS WILL NOT BE LIABLE FOR ANY CLAIM, INJURY OR DAMAGE ARISING IN CONNECTION WITH YOUR USE OF THE SERVICE OR THE THIRD PARTY SERVICES.
                </p>
                <p>
                    <b>REPRESENTATIONS AND WARRANTIES</b>By using the Software or Service, you expressly represent and warrant that you are legally entitled to enter this Agreement. If you reside in a jurisdiction which restricts the use of the Service because of age or restricts the ability to enter into agreements such as this one due to age, you must abide by such age limits or you must not use the Software and Service. Without limiting the foregoing, the Service and Software are not available to children (persons under the age of 18) or others who are not capable of entering into binding contracts, unless they have consent and permission of a parent or guardian. By using the Software or Service, you represent and warrant that you are at least 18 years old, or have the consent of a parent or guardian, and/or are otherwise capable of entering into binding contracts. By using the Software or the Service, you represent and warrant that you have the right, authority and capacity to enter into this Agreement and to abide by the terms and conditions of this Agreement. Your participation in using the Service and/or Software is for your sole, personal use. You may not authorize others to use your user status, and you may not assign or otherwise transfer your user account to any other person or entity. When using the Software or Service you agree to comply with all applicable laws from the country, state, and city in which you are present while using the Software or Service.
You may only access the Service using authorized means. It is your responsibility to check to ensure you download the correct Software for your device. The Company is not liable if you do not have a compatible handset or if you have downloaded the wrong version of the Software for your handset. By using the Software or the Service, you agree that:
You will only use the Service or Software for lawful purposes; you will not use the Service for sending or storing any unlawful material or for fraudulent purposes.
You will not use the Service or Software to cause nuisance, annoyance or inconvenience.
You will not impair the proper operation of the network.
You will not try to harm the Service or Software in any way whatsoever.
You will not copy, or distribute the Software or other content without written permission from the Company.
You will only use the Software and Service for your own use and will not resell it to a third party.
You will keep secure and confidential your account password or any identification provided to you which allows access to the Service.
You will provide us with whatever proof of identity the Company may reasonably request.
You will only use an access point or data account which you are authorized to use.
You will not portray Company or its affiliates in a negative manner or otherwise portray its services in a false, misleading, derogatory or offensive manner.
When requesting Third Party Services by SMS, you opt-in to receive text messages from the Company, and acknowledge that standard messaging charges from your mobile network service provider may apply, and you represent and warrant that the number provided is your own cell phone number.
You will not post or transmit any photograph or likeness of another person without that person's consent, if and to the extent necessary under applicable laws.
You will not post, publish, transmit, reproduce, distribute or in any way exploit any information, software or other material obtained through the Services for commercial purposes (other than as expressly permitted by the Service and by the provider of such information, software or other material).
You will not upload, post, publish, transmit, reproduce, or distribute in any way, information, software or other material obtained through the Services which is protected by copyright, or other proprietary right, or derivative works with respect thereto, without obtaining permission of the copyright owner or right holder, or which otherwise violates or infringes the rights of others, including without limitation, patent, trademark, trade secret, copyright, publicity, or other proprietary rights

                </p>
                <p>
                    <b>LICENSE GRANT & RESTRICTIONS</b> -The Company hereby grants you a non-exclusive, non-transferable, right to use the Software and Service, solely for your own personal, non-commercial purposes, subject to the terms and conditions of this Agreement. All rights not expressly granted to you are reserved by the Company and its licensors. You shall not (i) license, sublicense, sell, resell, transfer, assign, distribute or otherwise commercially exploit or make available to any third party the Service or the Software in any way; (ii) modify or make derivative works based upon the Service or the Software; (iii) create Internet "links" to the Service or "frame" or "mirror" any Software on any other server or wireless or Internet-based device; (iv) reverse engineer the Software; (v) access the Software or Services in order to (a) build a competitive product or service, (b) build a product using similar ideas, features, functions or graphics of the Service or Software, or (c) copy any ideas, features, functions or graphics of the Service or Software, or (vi) launch an automated program or script, including, but not limited to, web spiders, web crawlers, web robots, web ants, web indexers, bots, viruses or worms, or any program which may make multiple server requests per second, or unduly burdens or hinders the operation and/or performance of the Service or Software. You shall not: (i) send spam or otherwise duplicative or unsolicited messages in violation of applicable laws; (ii) send or store infringing, obscene, threatening, libelous, or otherwise unlawful or tortious material, including material harmful to children or violative of third party privacy rights; (iii) send or store material containing software viruses, worms, Trojan horses or other harmful computer code, files, scripts, agents or programs; (iv) interfere with or disrupt the integrity or performance of the Software or Service or the data contained therein; or (v) attempt to gain unauthorized access to the Software or Service or its related systems or networks
                </p>
                <p>
                    <b>CANCELLATION & REFUNDS POLICY (On-Demand Roadside Service)
</b>  - You may cancel your request for service to your location prior to driver arriving on scene. All cancellation are subject to payment of a $45 non-refundable charge. You will be charged the full amount of the quoted service price for any of the following cancellation instances/reasons: driver is on scene and you cancel for any reason; driver determines you have inaccurately stated the conditions of your vehicle thus the cost of service will be higher than initially quoted and you cancel service; you are Gone On Arrival (GOA) and/or fail to cancel service
                </p>
                <p>
                    <b>MEMBERSHIP SUBSCRIPTION TERMS</b> - For those purchasing a Mobile Roadside coverage plan, the following terms apply; Your use of Membership Subscription Services and Membership Subscription Products is governed by these Membership Subscription Terms, which are described in further detail below. The following points are particularly important:
Membership Subscriptions automatically renew until canceled.
You may cancel your Membership Subscription Product at any time by following the instructions included in your Membership Subscription Product purchase, redemption, or renewal confirmation email, all subject to the terms below.
Cancellation will cease auto-renewal of Membership Subscription and future payments, but previous Membership Subscription Fees are non-refundable except where required by law.
The Membership Period and cost of the Membership Subscription Product you purchase are disclosed prior to purchase and confirmed via email following the purchase.
We transfer your billing information to our payment processor(s) as disclosed in our Privacy Policy.
If your payment period is shorter than your Membership Period (i.e. monthly payments for an annual Membership Subscription), your payment method on file must remain current or your benefits will be suspended.
Offers may be subject to additional limitations, which are generally presented to you at the time of offer receipt.
Read these Membership Subscription Terms carefully before using the Membership Subscription Services. These Membership Subscription Terms (which include the other documents referenced below) constitute a legal agreement between you ("you" or "your") and MOBILE ROADSIDE. If you purchase, register for, or redeem a Membership Subscription Product through an External Partner of MOBILE ROADSIDE, you may also be subject to additional terms and conditions supplied by that service
                </p>
                <p>
                    <b>DRIVE | Roadside Service Coverage.</b> -  DRIVE roadside assistance has been designed to keep our members moving forward. Members are covered 24/7 through our nationwide preferred towing network of roadside assistance and towing professionals. Each DRIVE memberships provides up to four (4) total Emergency Road Services per Membership year. (With our monthly membership covering up to 1 roadside service every 3 months totalling 4 per year) A roadside service credit will be deducted each time a service is requested or when the membership expires.

                </p>
                 <p>
                    <b>DRIVE | Roadside Service Coverage.</b> -  DRIVE roadside assistance has been designed to keep our members moving forward. Members are covered 24/7 through our nationwide preferred towing network of roadside assistance and towing professionals. Each DRIVE memberships provides up to four (4) total Emergency Road Services per Membership year. (With our monthly membership covering up to 1 roadside service every 3 months totalling 4 per year) A roadside service credit will be deducted each time a service is requested or when the membership expires.

                </p>
                 <p>
                    <b>Towing.</b>- In the event of a mechanical disablement that renders a Covered Members Vehicle inoperable anywhere in the Territory, Policyholders may use our mobile application to arrange for a tow to the repair facility closest to the point of disablement. DRIVE will provide the dispatch service on an “indemnified” basis: the member requesting service will not be billed up to the coverage limits (10 miles). The member requesting services in excess of the coverage limits is responsible for any charges in excess of such limits. The member in the vehicle is responsible for any charges in excess of this limit. The overages charges will be set according to market rates. Services do NOT cover towing for salvage or standard maintenance (i.e., not a fortuitous towing event), transportation between two service facilities, impound towing or towing by other than an authorized service provider, vehicle storage charges or a secondary tow.


                </p>
                 <p>
                    <b>Battery Service/Minor Mechanical Disablement .</b> -  Vehicle Won't Start - In the event a Covered Vehicle is disabled due to a drained battery, a service call will be provided to conduct a jump-start in order to get the Covered Vehicle operating properly. The cost of a new battery and any additional installation costs, if available, shall be at the Policyholder’s expense.


                </p>
                 <p>
                    <b>Flat Tire Assistance  .</b> - In the event a Covered Vehicle has a flat tire and/or requires assistance in changing a tire with the Covered Vehicle’s good mounted spare tire, a service call will be issued to provide assistance. Coverage does not include a new tire. Any additional replacement costs, if available, shall be at the Policyholder’s expense.



                </p>
                 <p>
                    <b>Fuel, Oil, Fluid and Water Delivery Service </b> - - In the event a Covered Vehicle runs out of fuel or water while being operated, a service call will be provided to deliver an emergency supply of such fuel (up to two gallons included) or water to the disablement site, except where prohibited by law. Any additional cost of fuel (or other fluid costs) shall be the policyholder’s responsibility.


                </p>
                 <p>
                    <b>Lock-Out assistance .</b> -  In the event the operator of a Covered Vehicle locks the keys inside the vehicle, glovebox or trunk, a service call will be provided to assist in the opening of the locked vehicle. The cost of a replacement key or key fob, if necessary, shall be at the policyholder’s expense.
                </p>
                  <p>
                    <b>Extrication/Winch-out .</b> -  - DRIVE will arrange for the extraction by winch services of the Covered Vehicle that is within 10 feet of a maintained roadway. The service does not Cover Vehicles that: (i) require more than one light duty tow truck to provide the service, (ii) are involved in a vehicle recovery situation, (iii) have been submerged in water, or (iv) have been off-road four wheeling and are not on a maintained roadway.

                </p>
                <h2>. ELIGIBILITY REQUIREMENTS</h2>
                <p>To be eligible to access and use the Membership Subscription Services, you must meet the following criteria ("Eligibility Requirements"):
You must reside within the United States, the District of Columbia, or Puerto Rico be at least 18 years of age, and be capable of entering into a binding agreement;
You must have an account in good standing with Mobile Roadside, which includes the payment of all Fees and Applicable Taxes if any; and
You must meet any additional qualifications or adhere to any limitations disclosed with the offer of an applicable Membership Subscription Product, which we may update from time to time.
2. MEMBERSHIP SUBSCRIPTION
You may purchase Membership Subscription access (a "Membership Subscription") to the Membership Subscription Services for a fee (the "Fee"). The Fee is exclusive of any applicable federal, state, telecommunications, excise, or municipal taxes or duties, including VAT and GST (collectively, "Applicable Taxes") unless otherwise specified</p>
                <p>MOBILE ROADSIDE IS ONLY A VENUE</p>
                <p>The Service is a communications platform for enabling the connection between individuals seeking to obtain Third Party Services and/or individuals or companies seeking to provide Third Party Services. The Company does not guarantee or warrant, and makes no representations regarding, the reliability, quality or suitability of such Third Party Service Providers. When interacting with Third Party Service Providers you should exercise caution and common sense to protect your personal safety and property, just as you would when interacting with other persons whom you don't know. By using the Service, you agree to hold the Company free from the responsibility for any liability or damage that might arise out of the transactions involved. NEITHER THE COMPANY NOR ITS AFFILIATES OR LICENSORS IS RESPONSIBLE FOR THE CONDUCT, WHETHER ONLINE OR OFFLINE, OF ANY USER OF THE SERVICE OR THIRD PARTY SERVICES NOR ANY THIRD PARTY SERVICE PROVIDERS. THE COMPANY AND ITS AFFILIATES AND LICENSORS WILL NOT BE LIABLE FOR ANY CLAIM, INJURY OR DAMAGE ARISING IN CONNECTION WITH YOUR USE OF THE SERVICE OR THE THIRD PARTY SERVICES.</p>
                <p>REPRESENTATIONS AND WARRANTIES </p>

                
                        <h5>2. . USE AND RENEWAL</h5>
                        <p>Your ability to use the Membership Subscription Service commences on the date of your purchase, plus any applicable curing period, and continues until the end of the applicable Membership Period. Mobile Roadside will automatically renew or commence your Membership Subscription on the defined period of your Payment Period by charging the associated Fee plus any Applicable Taxes to the payment method you provided unless you cancel your Membership Subscription as provided below. Unless you affirmatively opt-out of automatic renewal either prior to the expiration of a Membership Subscription Product or before the end of the then-current Payment Period, you hereby authorize Mobile Roadside to renew or commence your Membership Subscription automatically at the end of each Membership Period or at the expiration of your Payment Period. If you opt-out of automatic renewal, your Membership Subscription Product will expire and your access to the Membership Subscription Services will cease at the end of the then-current Payment Period. In order to continue to access the Membership Subscription Services after your Payment Period has expired, you will need to purchase a new Membership Subscription Product. You are required to maintain accurate and up-to-date payment information. Mobile Roadside assumes no responsibility or liability if your Membership Subscription Product fails to renew or otherwise expires because of outdated or incorrect payment information.
</p>
                        <h5>3.. Membership REFUND POLICY
</h5>
                        <p>On-demand Roadside services are non-refundable after roadside request has been made and service provider has been dispatched. You may cancel the renewal of Membership Subscription Products at any time. Please email info@driveroadside.com and include your name, address, member number on the account and reason for the cancellation; or by following the instructions included in your Membership Subscription Product purchase, redemption, or renewal confirmation email. If you cancel your Membership Subscription Product during your current Payment Period, your access to the Membership Subscription Services will continue until the end of your then-current Payment Period, at which point it will expire. Purchase and/or redemption of your Membership Subscription Product is final and non-refundable; Mobile Roadside will not issue you any refund, including partial, pro-rated, or otherwise unless required to do so by law.
</p>
                        <h5>4. ADDITIONAL CHARGES:
 </h5>
                        <p>On-demand Roadside services are non-refundable after roadside request has been made and service provider has been dispatched.You may cancel the renewal of Membership Subscription Products at any time. Please email  info@driveroadside.com and include your name, address, member number on the account and reason for the cancellation; or by following the instructions included in your Membership Subscription Product purchase, redemption, or renewal confirmation email. If you cancel your Membership Subscription Product during your current Payment Period, your access to the Membership Subscription Services will continue until the end of your then-current Payment Period, at which point it will expire. Purchase and/or redemption of your Membership Subscription Product is final and non-refundable; Mobile Roadside will not issue you any refund, including partial, pro-rated, or otherwise unless required to do so by law. </p>
                        <h5>5. EXTERNAL SERVICES </h5>
                        <p>To the extent your description of the services needed and/or conditions impacting your vehicle are deficient, inaccurate or otherwise misstated and/or the services required are more extensive than your description indicated, the price quote provided through the Mobile Roadside application shall not be binding and you are responsible for paying for any additional services needed and/or requested.
For the avoidance of doubt: Mobile Roadside itself does not provide any roadside assistance or tow services, and Mobile Roadside is not a services carrier. Any roadside assistance and/or tow services are through the Provider. Mobile Roadside solely provides the platform through which you and the Provider can learn about each other. The provision of the services by the Provider to you is therefore subject to any agreement that you choose to enter into with the Provider. Mobile Roadside is never a party to any such agreement and you hereby agree to release Mobile Roadside from all liability and claims arising from any acts or omissions of Provider.
 </p>
                        <h5>6. . EXTERNAL SERVICES </h5>
                        <p>If you purchase or redeem a Membership Subscription Product through an External Partner, you must maintain accurate and up-to-date payment information with that External Partner in order to continue to access the Membership Subscription Services. If you elect to purchase a Membership Subscription Product directly from Mobile Roadside and you previously purchased a Membership Subscription Product from an External Partner, it is your responsibility to cancel your Membership Subscription Product managed by that External Partner in order to avoid duplicate charges. As disclosed above, purchase of a Membership Subscription Product is final and non-refundable except where the law requires Mobile Roadside to provide a refund, although the refund policy offered by External Partners may differ. Please refer to the External Partner through which you purchased a Membership Subscription Product for more details</p>
                        <h5>7. . AVAILABILITY AND MODIFICATIONS</h5>
                        <p>Mobile Roadside reserves the right to modify, offer additional, or cease offering Membership Subscription Products and Membership Subscription Services at any time in its sole discretion, including but not limited to changes in Fees, modifying the availability of and Eligibility Requirements for certain Membership Subscription Products and Membership Subscription Services, or modifying the features and functionality of certain Membership Subscription Services. If we cease offering your current Membership Subscription Product, your access to the Membership Subscription Services will continue until the end of your Membership Period. In such event, we may elect to migrate you to a similar Membership Subscription Product and charge your payment method the associated Fee at the end of your Membership Period. We will provide you with thirty (30) days prior notice via email before changes in Membership Subscription Products or Fees take effect. This may vary by State. Please review your Membership Subscription Product’s Terms and Conditions. Any changes to the Membership Subscription Products or Fees will be effective upon your next billing cycle tied to the start of the Membership Period, and will not apply retroactively to your current Membership Period. In the event we do migrate you to a different Membership Subscription Product or modify your Fee, you may opt-out of these changes by canceling your Membership Subscription Product.
 </p>
                        <h5>8. . CHANGES TO MEMBERSHIP SUBSCRIPTION TERMS </h5>
                        <p>We may modify these Membership Subscription Terms from time to time. If we make material changes to these Membership Subscription Terms as it applies to your currently active Membership Subscription Product, then we will supply you with appropriate notice of those changes. Revised Membership Subscription Terms will become effective upon the next renewal of your Membership Subscription Product and your continued use of the Membership Subscription Services will constitute your acceptance of the revised terms. If you are not willing to agree to the revisions, you may cancel your Membership Subscription Product as disclosed in Section 4 above</p>
                        <h5>9. . MEMBERSHIP SUBSCRIPTION ISSUER</h5>
                        <p>Mobile Roadside is the issuer of Membership Subscription Products in the United States and its related territories. Roadside Innovation Inc., a wholly-owned subsidiary of Mobile Roadside, LLC., is the Obligor. Mobile Roadside, LLC reserves the right to assign Obligor to a third-party as required by law. Consult your specific Membership Subscription Product for details.
</p>
                        <h5>FEES AND PAYMENT TERMS (ON-DEMAND SERVICES & OVERAGE AMOUNTS) </h5>
                        <p>Company or the Third Party Service provider may charge you, on behalf of the Third Party Service Provider for the Third Party Services provided to you by the Third Party Service Provider. You agree that you will pay for all Third Party Services you purchase from the Third Party Service Provider, and that Company or Third Party Service Provider may charge your credit card account as provided by you when registering for the Service (including any taxes and late fees, as applicable) that may be accrued by or in connection with your account. You are responsible for the timely payment of all fees and for providing Company with a valid credit card account for payment of all fees at all times. You must keep all billing information, including payment method, up to date. You authorize and direct us to charge your designated payment method for these charges or, if your designated payment method fails, to charge any other payment method you have on file with us. Further, you authorize and direct us to retain information about the payment method(s) associated with your account. If we do not receive payment from your designated payment method or any other payment method on file, you agree to pay all amounts due upon demand by us. After 30 days from the date of any unpaid charges, your payment will be deemed delinquent and we reserve the right to assess an additional 1.5 percent late charge (or the highest amount allowed by law, whichever is lower) per month if your payment is more than 30 days past due and to use any lawful means to collect any unpaid charges. You are liable for any fees, including attorney and collection fees, incurred by us in our efforts to collect any remaining balances from you. You are responsible for all charges incurred under your account, including applicable taxes, fees, surcharges, and purchases made by you or anyone you allow to use your account (including your children, family, friends, or any other person with implied, actual, or apparent authority) or anyone who gains access to your account as a result of your failure to safeguard your username, password, or other authentication credentials or information</p>
                        <p>Company may use a third-party payment processor (the “Payment Processor”) to link your credit card account to the Service. The processing of payments or credits, as applicable, in connection with your use of the Service will be subject to the terms, conditions and privacy policies of the Payment Processor and your credit card issuer in addition to this Agreement. Company is not responsible for any errors by the Payment Processor. In connection with your use of the Service, Company will obtain certain transaction details, which Company will use solely in accordance with its Privacy Policy.</p>
                        <p>Any fees which the Company or Third Party Service Provider may charge you for the Software or Service or Third Party Services are due immediately upon completion of your applicable use of the Software, Service or the Third Party Service transaction and are non-refundable. This no refund policy shall apply at all times regardless of your decision to terminate your usage, the Company's decision to terminate your usage, disruption caused to our Software or Service either planned, accidental or intentional, or any reason whatsoever. The Company reserves the right to determine final prevailing pricing - Please note the pricing information published on the website may not reflect the prevailing pricing. The Company, at its sole discretion, make promotional offers with different features and different rates to any of our customers. These promotional offers, unless made to you, shall have no bearing whatsoever on your offer or contract. The Company may change the fees for our Service as we deem necessary for our business. We encourage you to check back at our website periodically if you are interested about how we charge for the Service. We may not be responsible for determining fees charged by Third Party Service providers, so you should be sure to review all pricing and other terms of any agreement or transaction you conduct with them.</p>
                        <h5>PUBLIC POSTINGS </h5>
                        <p>Certain material you may post on our Services is or may be available to the public, including without limitation any public profile data, uploads, blog entries, ratings, reviews, images, videos, poll answers, and any other user-generated content, in any form or media, that you post via the Service or otherwise (collectively, "Public Postings"). These Public Postings will be treated as non-confidential and nonproprietary. You are responsible for any Public Postings and the consequences of sharing or publishing such content with others or the general public. This includes, for example, publicly sharing any personal information, such as your home address, the home address of others, or your current location. COMPANY IS NOT RESPONSIBLE FOR THE CONSEQUENCES OF PUBLICLY SHARING OR POSTING ANY PERSONAL OR OTHER INFORMATION ON THE SERVICES.</p>
                        <p>Other content or communications you privately transmit to Company, including without limitation any feedback, data, questions, comments, suggestions, in any form or media, that you submit to us via e-mail, the Services or otherwise (collectively, "Submissions"), will be treated as non-confidential and nonproprietary, except if and to the extent otherwise expressly required in our Privacy Policy, with respect to any personally identifiable information privately submitted to us. </p>
                        <p>By providing any Public Posting or Submission, you (i) grant to Company a royalty-free, non-exclusive, perpetual, irrevocable, sub-licensable right to use, reproduce, modify, adapt, publish, translate, create derivative works (including products) from, distribute, and display such content throughout the world in all media and you license to use all patent, trademark, trade secret, copyright or other proprietary rights in and to such content for publication on the Service pursuant to this Agreement; (ii) agree that Company shall be free to use any ideas, concepts or techniques embodied therein for any purpose whatsoever, including, but not limited to, developing and marketing products or services incorporating such ideas, concepts, or techniques, without attribution, without any liability or obligation to you; (iii) grant to Company the right to use the name that you submit in connection with such content. In addition, you hereby waive all moral rights you may have in any Public Posting or Submissions.</p>
                        <p>You shall be solely responsible for your own content and any Pubic Postings and Submissions. You affirm, represent, and warrant that you own or have the necessary licenses, rights, consents, and permissions to publish content you post or submit. You further agree that content you submit via Public Postings or Submissions will not contain third party copyrighted material, or material that is subject to other third party proprietary rights, unless you have permission from the rightful owner of the material or you are otherwise legally entitled to post the material and to grant us all of the license rights granted herein. You further agree that you will not submit to the Service any content or other material that is contrary to our community guidelines, which may be updated from time to time, or contrary to applicable local, national, and international laws and regulations. Company does not endorse any content submitted to the Service by any user or other licensor, or any opinion, recommendation, or advice expressed therein, and Company expressly disclaims any and all liability in connection with the content. We do not permit copyright infringing activities and infringement of intellectual property rights on the Service, and we will remove all content if properly notified that such content infringes on another's intellectual property rights. We reserve the right to remove content without prior notice. Company reserves the right to decide whether your content violates this Agreement for reasons other than copyright infringement, such as, but not limited to, pornography, obscenity, or excessive length. Company may at any time, without prior notice and in our sole discretion, remove such content and/or terminate a user's account for submitting such material in violation of this Agreement.</p>
                        <h5>INTELLECTUAL PROPERTY OWNERSHIP </h5>
                        <p>The Company alone (and its licensors, where applicable) shall own all right, title and interest, including all related intellectual property rights, in and to the Software and the Service. To the extent you provide any suggestions, ideas, enhancement requests, feedback, and recommendations or other information regarding the Service or Software, you hereby assign to the Company all right, title and interest thereto. This Agreement is not a sale and does not convey to you any rights of ownership in or related to the Software or the Service, or any intellectual property rights owned by the Company. The Company name, the Company logo, and the product names associated with the Software and Service are trademarks of the Company or third parties, and no right or license is granted to use them.</p>
                        <h5>PRIVACY; DIGITAL MILLENNIUM COPYRIGHT ACT (DMCA) </h5>
                        <p>The Company’s Privacy Policy posted on our website is hereby incorporated by reference and made a part of this Agreement. Please review our separate Privacy Policy to understand how the Company collects and uses personal information. The Digital Millennium Copyright Act of 1998 (the "DMCA") provides recourse for copyright owners who believe that material appearing on the Internet infringes their rights under U.S. copyright law. If you believe in good faith that any content made available in connection with the Service or Software infringes your copyright, you (or your agent) may send the Company a notice requesting that the content be removed, or access to it blocked. Notices and counter-notices must meet the then-current statutory requirements imposed by the DMCA (see http://www.loc.gov/copyright for details). DMCA notices and counter-notices with respect to the Service or Software should be sent to the Company at info@driveroadside.com </p>
                        <h5>THIRD PARTY INTERACTIONS </h5>
                        <p>During use of the Software and Service, you may enter into correspondence with, purchase goods and/or services from, or participate in promotions of third party service providers, advertisers or sponsors showing their goods and/or services through the Software or Service. Any such activity, and any terms, conditions, warranties or representations associated with such activity, is solely between you and the applicable third-party. The Company and its licensors shall have no liability, obligation or responsibility for any such correspondence, purchase, transaction or promotion between you and any such third-party. The Company does not endorse any sites on the Internet that are linked through the Service or Software, and in no event shall the Company or its licensors be responsible for any content, products, services or other materials on or available from such sites or third party providers. The Company provides the Software and Service to you pursuant to the terms and conditions of this Agreement. You recognize, however, that certain third-party providers of goods and/or services may require your agreement to additional or different terms and conditions prior to your use of or access to such goods or services, and the Company disclaims any and all responsibility or liability arising from such agreements between you and the third party providers.</p>
                        <p>The Company may rely on third-party advertising and marketing supplied through the Software or Service and other mechanisms to subsidize the Software or Service. By agreeing to these terms and conditions you agree to receive such advertising and marketing. The Company may compile and release information regarding you and your use of the Software or Service on an anonymous basis as part of a customer profile or similar report or analysis. You agree that it is your responsibility to take reasonable precautions in all actions and interactions with any third party you interact with through the Service.</p>
                        <p>You will be responsible for your own connectivity to the Service, including without limitation via a mobile connection, internet access, and other communications and connectivity, at your own cost and expense. Depending on your method of access, additional messaging or data rates may apply from your carrier.</p>
                        <p>If you are using Software such as a mobile app, additional terms and conditions may apply in accordance with the terms and conditions of the applicable app store from which you downloaded the Software.</p>
                        <h5>INDEMNIFICATION</h5>
                        <p>By entering into this Agreement and using the Software or Service, you agree to defend, indemnify and hold the Company, its licensors and each such party's parent organizations, subsidiaries, affiliates, officers, directors, members, employees, attorneys and agents harmless from and against any and all claims, costs, damages, losses, liabilities and expenses (including attorneys' fees and costs) arising out of or in connection with: (a) your violation or breach of any term of this Agreement or any applicable law or regulation, whether or not referenced herein; (b) your violation of any rights of any third party, including providers of Third Party Services arranged via the Service or Software, or (c) your use or misuse of the Software or Service or any Third Party Service.</p>
                        <h5>TERMINATION</h5>
                        <p>The Company reserves the right to (i) modify or discontinue, temporarily or permanently, the Service (or any part thereof) and (ii) refuse any and all current and future use of the Service, suspend or terminate your account (any part thereof) or use of the Service, for any reason, including if the Company believes that you have violated this Agreement. The Company shall not be liable to you or any third party for any modification, suspension or discontinuation of the Service.</p>
                        <h5>DISCLAIMER OF WARRANTIES </h5>
                        <h5>THE COMPANY MAKES NO REPRESENTATION, WARRANTY, OR GUARANTY AS TO THE RELIABILITY, TIMELINESS, QUALITY, SUITABILITY, AVAILABILITY, ACCURACY OR COMPLETENESS OF THE SERVICE OR SOFTWARE (OR ANY THIRD PARTY SERVICES). THE COMPANY DOES NOT REPRESENT OR WARRANT THAT (A) THE USE OF THE SERVICE OR SOFTWARE WILL BE SECURE, TIMELY, UNINTERRUPTED OR ERROR-FREE OR OPERATE IN COMBINATION WITH ANY OTHER HARDWARE, SOFTWARE, SYSTEM OR DATA, (B) THE SERVICE OR SOFTWARE (OR ANY THIRD PARTY SERVICES) WILL MEET YOUR REQUIREMENTS OR EXPECTATIONS, (C) ANY STORED DATA WILL BE ACCURATE OR RELIABLE, (D) THE QUALITY OF ANY PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE SERVICE (INCLUDING ANY THIRD PARTY SERVICES) WILL MEET YOUR REQUIREMENTS OR EXPECTATIONS, (E) ERRORS OR DEFECTS IN THE SERVICE OR SOFTWARE WILL BE CORRECTED, OR (F) THE SERVICE OR THE SERVER(S) THAT MAKE THE SERVICE AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. THE SERVICE AND SOFTWARE ARE PROVIDED TO YOU STRICTLY ON AN "AS IS" BASIS. ALL CONDITIONS, REPRESENTATIONS, AND WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT OF THIRD PARTY RIGHTS, ARE HEREBY DISCLAIMED TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW BY THE COMPANY. THE COMPANY MAKES NO REPRESENTATION, WARRANTY, OR GUARANTY AS TO THE RELIABILITY, SAFETY, TIMELINESS, QUALITY, SUITABILITY OR AVAILABILITY OF ANY THIRD PARTY SERVICES. YOU ACKNOWLEDGE AND AGREE THAT THE ENTIRE RISK ARISING OUT OF YOUR USE OF THE SOFTWARE AND SERVICE, AND ANY THIRD PARTY SERVICES, REMAINS SOLELY WITH YOU, TO THE MAXIMUM EXTENT PERMITTED BY LAW.</h5>
                        <h5>NETWORK DELAYS </h5>
                        <h5>THE COMPANY'S SERVICE AND SOFTWARE MAY BE SUBJECT TO LIMITATIONS, DELAYS, AND OTHER PROBLEMS INHERENT IN THE USE OF THE INTERNET, TELECOMMUNICATIONS NETWORKS AND ELECTRONIC COMMUNICATIONS. THE COMPANY IS NOT RESPONSIBLE FOR ANY DELAYS, DELIVERY FAILURES, OR OTHER DAMAGE RESULTING FROM SUCH PROBLEMS.</h5>
                        <h5>LIMITATION OF LIABILITY </h5>
                        <h5>IN NO EVENT SHALL THE COMPANY'S AGGREGATE LIABILITY EXCEED THE AMOUNTS ACTUALLY PAID BY AND/OR DUE FROM YOU IN THE SIX (6) MONTH PERIOD IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO SUCH CLAIM. IN NO EVENT SHALL THE COMPANY AND/OR ITS LICENSORS BE LIABLE TO ANYONE FOR ANY INDIRECT, PUNITIVE, SPECIAL, EXEMPLARY, INCIDENTAL, CONSEQUENTIAL OR OTHER DAMAGES OF ANY TYPE OR KIND (INCLUDING PERSONAL INJURY, LOSS OF DATA, REVENUE, PROFITS, USE OR OTHER ECONOMIC ADVANTAGE). THE COMPANY AND/OR ITS LICENSORS SHALL NOT BE LIABLE FOR ANY LOSS, DAMAGE OR INJURY WHICH MAY BE INCURRED BY YOU, INCLUDING BY NOT LIMITED TO LOSS, DAMAGE OR INJURY ARISING OUT OF, OR IN ANY WAY CONNECTED WITH THE SERVICE OR SOFTWARE, INCLUDING BUT NOT LIMITED TO THE USE OR INABILITY TO USE THE SERVICE OR SOFTWARE, ANY RELIANCE PLACED BY YOU ON THE COMPLETENESS, ACCURACY OR EXISTENCE OF ANY ADVERTISING, OR AS A RESULT OF ANY RELATIONSHIP OR TRANSACTION BETWEEN YOU AND ANY THIRD PARTY SERVICE PROVIDER, ADVERTISER OR SPONSOR WHOSE ADVERTISING APPEARS ON THE WEBSITE OR IS REFERRED BY THE SERVICE OR SOFTWARE, EVEN IF THE COMPANY AND/OR ITS LICENSORS HAVE BEEN PREVIOUSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</h5>
                        <h5>THE COMPANY MAY INTRODUCE YOU TO THIRD PARTY SERVICE PROVIDERS FOR THE PURPOSES OF PROVIDING THIRD PARTY SERVICES. WE WILL NOT ASSESS THE SUITABILITY, LEGALITY OR ABILITY OF ANY THIRD PARTY SERVICE PROVIDERS AND YOU EXPRESSLY WAIVE AND RELEASE THE COMPANY FROM ANY AND ALL ANY LIABILITY, CLAIMS OR DAMAGES ARISING FROM OR IN ANY WAY RELATED TO THE THIRD PARTY SERVICE PROVIDER. THE COMPANY WILL NOT BE A PARTY TO DISPUTES OR NEGOTIATIONS BETWEEN YOU AND SUCH THIRD PARTY PROVIDERS. RESPONSIBILITY FOR THE DECISIONS YOU MAKE REGARDING THIRD PARTY SERVICES OFFERED VIA THE SOFTWARE OR SERVICE (WITH ALL ITS IMPLICATIONS) RESTS SOLELY WITH YOU. WE WILL NOT ASSESS THE SUITABILITY, LEGALITY OR ABILITY OF ANY SUCH THIRD PARTIES AND YOU EXPRESSLY WAIVE AND RELEASE THE COMPANY FROM ANY AND ALL LIABILITY, CLAIMS, CAUSES OF ACTION, OR DAMAGES ARISING FROM YOUR USE OF THE SOFTWARE OR SERVICE, OR IN ANY WAY RELATED TO THE THIRD PARTIES INTRODUCED TO YOU BY THE SOFTWARE OR SERVICE. YOU EXPRESSLY WAIVE AND RELEASE ANY AND ALL RIGHTS AND BENEFITS UNDER SECTION 1542 OF THE CIVIL CODE OF THE STATE OF CALIFORNIA (OR ANY ANALOGOUS LAW OF ANY OTHER STATE), WHICH READS AS FOLLOWS: "A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH, IF KNOWN BY HIM, MUST HAVE MATERIALLY AFFECTED HIS SETTLEMENT WITH THE DEBTOR."</h5>
                        <h5>THE QUALITY OF THE THIRD PARTY SERVICES SCHEDULED THROUGH THE USE OF THE SERVICE OR SOFTWARE IS ENTIRELY THE RESPONSIBILITY OF THE THIRD PARTY PROVIDER WHO ULTIMATELY PROVIDES SUCH THIRD PARTY SERVICES TO YOU. YOU UNDERSTAND, THEREFORE, THAT BY USING THE SOFTWARE AND THE SERVICE, YOU MAY BE EXPOSED TO THIRD PARTY SERVICES THAT ARE POTENTIALLY DANGEROUS, OFFENSIVE, HARMFUL TO MINORS, UNSAFE OR OTHERWISE OBJECTIONABLE, AND THAT YOU USE THE SOFTWARE AND THE SERVICE, AND SUCH THIRD PARTY SERVICES, AT YOUR OWN RISK.</h5>
                        <h5>NOTHING ON THIS WEBSITE CONSTITUTES, OR IS MEANT TO CONSTITUTE, ADVICE OF ANY KIND. IF YOU REQUIRE ADVICE IN RELATION TO ANY LEGAL, FINANCIAL OR MEDICAL MATTER YOU SHOULD CONSULT AN APPROPRIATE PROFESSIONAL. BY USING THE SERVICE OR SOFTWARE, YOU AGREE THAT THE EXCLUSIONS AND LIMITATIONS OF LIABILITY SET OUT IN THIS AGREEMENT ARE REASONABLE. IF YOU DO NOT THINK THEY ARE REASONABLE, YOU MUST NOT USE THE SERVICE OR SOFTWARE.</h5>
                        <h5>NOTICE</h5>
                        <p>The Company may give notice to you by means of a general notice on a portion of the Service (which may include posting on the Company website), electronic mail to your email address on record in the Company's account information, or by written communication sent by first class mail or pre-paid post to your address on record in the Company's account information. Such notice shall be deemed to have been given upon the expiration of 48 hours after mailing (if sent by first class mail or pre-paid post) or 12 hours after sending (if sent by email) or posting. You may give notice to the Company only in writing (such notice shall be deemed given only when actually received by the Company).</p>
                        <h5>INTERNATIONAL USE</h5>
                        <p>The Service is controlled, operated and administered by us from within the United States. The company makes no representation that this site is available for access or use at other locations outside the U.S. However, any access or use from outside the U.S. is still subject to this Agreement. Access to this Service is expressly prohibited from territories where this site or any portion thereof is illegal. You agree not to access or use any information or materials on the Service in violation of U.S. export laws and regulations or in violation of any laws or regulations in the country from which you are accessing the Service.</p>
                        <h5>OTHER PARTIES</h5>
                        <p>You accept that, as a corporation, the Company has an interest in limiting the personal liability of its officers and employees. You agree that you will not bring any claim personally against the Company's officers or employees in respect of any losses you suffer in connection with the Service or Software. Without prejudice to the foregoing, you agree that the limitations of warranties and liability set out in this Agreement will protect the Company's officers, employees, agents, subsidiaries, successors, assigns and sub-contractors as well as the Company.</p>
                        <h5>BREACHES OF THESE TERMS AND CONDITIONS </h5>
                        <p>Without prejudice to the Company's other rights under these terms and conditions, if you breach these terms and conditions in any way, the Company may take such action as the Company deems appropriate to deal with the breach, including suspending your access to the Service or Software, prohibiting you from accessing the Service or Software, blocking computers using your IP address from accessing the Service or Software, contacting your internet service provider to request that they block your access to the Service or Software and/or bringing court proceedings against you.</p>
                        <h5>ASSIGNMENT</h5>
                        <p>This Agreement may not be assigned by you without the prior written approval of the Company but may be assigned without your consent by the Company to (i) a parent or subsidiary, (ii) an acquirer of assets, or (iii) any other successor or acquirer. Any purported assignment in violation of this section shall be void. In the event that Company is sold to a third party, such a sale will not be deemed a transfer of personal information so long as that third party agrees to assume Company's obligations as to this Agreement and any associated Privacy Policy. </p>
                        <h5>GOVERNING LAW </h5>
                        <p>Except as expressly provided otherwise, this Agreement will be is governed by, and will be construed under, the laws of the State of Virginia, without regard to choice of law principles. You consent to jurisdiction and venue exclusively in the courts in Northern Virginia. You agree that Company retains the right to seek injunctive or other equitable relief in a court of competent jurisdiction to prevent the actual or threatened infringement, misappropriation or violation of a party's copyrights, trademarks, trade secrets, patents, or other intellectual property rights. You agree that regardless of any statute or law to the contrary, any claim or cause of action arising out of this Agreement or related to use of the Service must be filed by you within three (3) months after such claim or cause of action arose or be forever barred.</p>
                        <h5>GENERAL</h5>
                        <p>No joint venture, partnership, employment, or agency relationship exists between you, the Company or any third party provider as a result of this Agreement or use of the Service or Software. If any provision of the Agreement is held to be invalid or unenforceable, such provision shall be struck and the remaining provisions shall be enforced to the fullest extent under law. The failure of the Company to enforce any right or provision in this Agreement shall not constitute a waiver of such right or provision unless acknowledged and agreed to by the Company in writing. This Agreement comprises the entire agreement between you and the Company and supersedes all prior or contemporaneous negotiations, discussions or agreements, whether written or oral, between you and the Company regarding the subject matter contained herein.</p>
                    </ul>
                </ul>
            </div>
        </div>
    </section>
@endsection

@section('footer')
@endsection

@section('js')
@endsection

