<?php include'include/header.php'; ?>
<?php include'include/sidebar.php'; ?>
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Dashboard
            <small>Control panel</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li class="active">Dashboard</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <!-- Small boxes (Stat box) -->
        <?php include'include/messages.php'; ?>
        <div class="row">
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-aqua">
                    <div class="inner">
                    <?php // dd($user_count); ?>
                        <h3><?= (isset($user_count)) ? $user_count : '' ?></h3>

                        <p>Users</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-bag"></i>
                    </div>
                    <a href="<?= asset('users');?>" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                      
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-green">
                    <div class="inner">
                        <h3><?= (isset($active_subscription)) ? $active_subscription : ''?></h3>
                        <p>Active Subscriptions</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-stats-bars"></i>
                    </div>
                    <a href="<?= asset('subscriptions');?>" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                  
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-blue">
                    <div class="inner">
                        <h3><?= (isset($renew_counter)) ? $renew_counter : ''?></h3>
                        <p>Renew Subscriptions</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-stats-bars"></i>
                    </div>
                    <?php 
                        /*
                    <a href="<?= asset('subscriptions');?>" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                  
                      */
                    ?>
                </div>
            </div>
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-red">
                    <div class="inner">
                        <h3><?= (isset($inactive_subscription)) ? $inactive_subscription : ''?></h3>
                        <p>Inactive Subscriptions</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-stats-bars"></i>
                    </div>
                    <?php 
                        /*
                    <a href="<?= asset('subscriptions');?>" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                  
                      */
                    ?>
                </div>
            </div>
        </div>
        <!-- /.row -->
        <!-- 2nd row -->
        <div class="row">
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-green">
                    <div class="inner">
                    <?php // dd($user_count); ?>
                        <h3><?= (isset($toal_revenue)) ? '$'.$toal_revenue : '' ?></h3>

                        <p>Total Revenue</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-bag"></i>
                    </div>
                    <?php 
                        /*
                    <a href="<?= asset('users');?>" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                      */
                    ?>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-green">
                    <div class="inner">
                        <h3>$<?= (isset($pay_total_year)) ? $pay_total_year : ''?></h3>
                        <p>Revenue Generated By Year</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-stats-bars"></i>
                    </div>
                    <?php 
                        /*
                    <a href="<?= asset('subscriptions');?>" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                  
                      */
                    ?>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-green">
                    <div class="inner">
                        <h3>$<?= (isset($pay_total_quater)) ? $pay_total_quater : ''?></h3>
                        <p>Revenue Generated By Quarter</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-stats-bars"></i>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-green">
                    <div class="inner">
                        <h3>$<?= (isset($pay_total_month)) ? $pay_total_month : ''?></h3>
                        <p>Revenue Generated By Month</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-stats-bars"></i>
                    </div>
                </div>
            </div>
        </div>
        <!-- 3rd row -->
        <div class="row">
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-green">
                    <div class="inner">
                    <?php // dd($user_count); ?>
                        <h3>$<?= (isset($pay_total_week)) ? $pay_total_week : '' ?></h3>

                        <p>Revenue Generated By Week</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-bag"></i>
                    </div>
                    <?php 
                        /*
                    <a href="<?= asset('users');?>" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                      */
                    ?>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-green">
                    <div class="inner">
                        <h3>$<?= (isset($pay_total_day)) ? $pay_total_day : ''?></h3>
                        <p>Revenue Generated By Today</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-stats-bars"></i>
                    </div>
                    <?php 
                        /*
                    <a href="<?= asset('subscriptions');?>" class="small-box-footer">More info <i class="fa fa-arrow-circle-right"></i></a>
                  
                      */
                    ?>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-aqua">
                    <div class="inner">
                        <h3><?= (isset($churn_date)) ? $churn_date : ''?>%</h3>
                        <p>Last 12 Months Churn Rate</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-stats-bars"></i>
                    </div>
                </div>
            </div>
            <!-- ./col -->
            <div class="col-lg-3 col-xs-6">
                <!-- small box -->
                <div class="small-box bg-primary">
                    <div class="inner">
                        <h3>$<?= (isset($life_time_value)) ? $life_time_value : ''?></h3>
                        <p>Expected Lifetime Value (10 Years)</p>
                    </div>
                    <div class="icon">
                        <i class="ion ion-stats-bars"></i>
                    </div>
                </div>
            </div>
            <!-- ./col -->
        </div>
        <!-- Main row -->
        <div class="row">
            <!-- Left col -->
            <?php /*
            <section class="col-lg-7 connectedSortable">
                <!-- quick email widget -->
                <div class="box box-info">
                    <div class="box-header">
                        <i class="fa fa-envelope"></i>

                        <h3 class="box-title">Create Subscription</h3>
                         tools box 
                        <div class="pull-right box-tools">
                            <button type="button" class="btn btn-info btn-sm" data-widget="remove" data-toggle="tooltip" title="Remove">
                                <i class="fa fa-times"></i></button>
                        </div>
                         /. tools 
                    </div>

                    <div class="col-lg-4">
                        <a href="<?= asset('test_card_token'); ?>" class="btn btn-primary">Test Card Token</a>
                        <a href="<?= asset('get_subscription_plan'); ?>" class="btn btn-info">Retrieve Subscription</a>
                        <a href="<?= asset('all_subscriptions'); ?>" class="btn btn-primary">Retrieve All Subscriptions</a>
                    </div>
                    <div class="box-body">
                        <form action="<?= asset('create_subscription'); ?>" method="post">
                            <?= csrf_field(); ?>
                            <div class="form-group">
                                <input type="text" class="form-control" name="token" placeholder="Customer Token">
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" name="id" placeholder="User Id">
                            </div>
                            <input type="submit" value="Creat Subscription">
                        </form>-->
                        <?php
                        if (isset($subscription)) {
                            echo date('m/d/Y', strtotime($subscription->start_date));
                        } else if (isset($subscriptions)) {
                            foreach ($subscriptions as $subscription) {
                                ?>
                                <td><?= date('m/d/Y', strtotime($subscription->start_date)); ?></td></br>
                                <?php
                            }
                        }
                        ?>
<!--                    </div>

                </div>
                                    
            </section>

             */
            ?>
            <!-- /.Left col -->

            <!-- right col (We are only adding the ID to make the widgets sortable)-->
            <!-- right col -->
        </div>
        <!-- /.row (main row) -->

    </section>
    <!-- /.content -->
</div>

<?php include'include/footer.php'; ?>